- hosts: all
  become: true

  vars_files:
    - vars/default.yml

  vars:
    pip_install_packages:
      - name: ansible
      - name: docker
      - name: docker-compose
    nodejs_npm_global_packages:
      - name: npm

  pre_tasks:
    - name: Update apt cache.
      apt:
         update_cache: yes
         cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - role: geerlingguy.git
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: geerlingguy.nodejs
    - role: awx
