- hosts: all
  become: true

  vars_files:
    - vars/main.yml

  vars:
    pip_install_packages:
      - name: pip
        version: "9.0.3"
        state: forcereinstall
      - name: ipify
      - name: pip
        state: latest
      - name: docker
      - name: ansible
      - name: ansible-tower-cli
      - name: docker-compose
        version: "1.24.1"
    nodejs_npm_global_packages:
      - name: npm

  pre_tasks:
    - name: Update apt cache.
      apt:
         update_cache: yes
         cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - role: geerlingguy.git
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: geerlingguy.nodejs
    - role: awx
