- name: Retrieve Ansible AWX installer
  git:
    repo: '{{ awx_repo_url }}'
    dest: '{{ work_dir }}'
    version: '{{ awx_repo_version }}'

- name: Install Ansible AWX
  command: ansible-playbook -i inventory install.yml
  args:
    chdir: "{{ work_dir }}/installer"
